# Generated by Django 5.2.14 on 2026-06-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurateur', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
