# Generated by Django 5.2.14 on 2026-06-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_fill_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('assembling', 'Собирается рестораном'), ('delivery', 'Передан курьеру'), ('done', 'Выполнен')], db_index=True, default='unprocessed', max_length=20, verbose_name='статус'),
        ),
    ]
