# Generated by Django 5.2.14 on 2026-06-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('electronic', 'Электронно'), ('cash', 'Наличностью')], db_index=True, default='', max_length=20, verbose_name='способ оплаты'),
        ),
    ]
